version: "3"
services:

  db:
    image: mariadb
    restart: always
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: openplant:latest
    build:
      context: ./app/
    volumes:
      - ./alembic:/app/alembic
    env_file:
      - db.env
      - incubator.env
    depends_on:
      - db

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000

volumes:
  db-data:

