version: '3'
services:
  app:
    image: openplant:latest
    build:
      context: ./app/
    volumes:
      - "./alembic:/app/alembic"
    env_file:
      - db.env
  db:
    container_name: openplant_db
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: openplant
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - openplant-data:/var/lib/mysql

volumes:
  openplant-data: {}

